---
swagger: "2.0"
info:
  description: "Basic todo API for learning swagger"
  version: "0.1.0"
  title: "Todo API"
  contact:
    name: "Anton"
    url: "http://github.com/Sinoptik21"
    email: "rus-21region@mail.ru"
host: "localhost:10010"
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: "The GET method for the root endpoint returns all todos available\
        \ in the database. The response includes the todo, date created, author, due\
        \ date, tags, and completed status."
      operationId: "getAllTodos"
      parameters: []
      responses:
        200:
          description: "An array of todos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
      x-swagger-router-controller: "getAllTodos"
    post:
      description: "Add a new Todo"
      operationId: "addTodo"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "todo"
        description: "the Todo tem to be added"
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        200:
          description: "Successful Todo add"
      x-swagger-router-controller: "addTodo"
  /todo/{id}:
    get:
      description: "Retrieve a single todo via the id supplied in the path"
      operationId: "findTodoById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id of the todo to get"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Todo response"
          schema:
            $ref: "#/definitions/Todo"
      x-swagger-router-controller: "findTodoById"
    delete:
      description: "deletes a single todo based on the supplied id"
      operationId: "deleteTodoById"
      parameters:
      - name: "id"
        in: "path"
        description: "id of the todo deleted"
        required: true
        type: "integer"
        format: "int64"
      responses:
        204:
          description: "Todo deleted"
      x-swagger-router-controller: "deleteTodoById"
    put:
      description: "update a single todo by id"
      operationId: "updateTodoById"
      parameters:
      - name: "id"
        in: "path"
        description: "id of the todo being updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "updated_todo"
        description: "the updated todo"
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        200:
          description: "Todo updated"
        400:
          description: "Yikes! An error!"
      x-swagger-router-controller: "updateTodoById"
definitions:
  Todo:
    type: "object"
    properties:
      todo_id:
        type: "integer"
        description: "Id for the Todo item. Generated by the database"
      todo:
        type: "string"
        description: "The text of the todo item as entered by"
      datecreated:
        type: "string"
        format: "date-time"
        description: "The timestamp when the todo was created. You don't need to supply\
          \ this, it is automatically set by the server."
      author:
        type: "string"
        description: "The name of the author or owner of the todo"
      duedate:
        type: "string"
        format: "date-time"
        description: "The timestamp when the Todo is due"
      tags:
        type: "array"
        items:
          type: "string"
      completed:
        type: "boolean"
        description: "Indicates if the todo has been completed"
